// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZK1j9-lzlYvnjbXS29DxemNcPf1whWM',
    appId: '1:584735660993:web:9094625828021cc18f2d40',
    messagingSenderId: '584735660993',
    projectId: 'expense-tracker-70ad9',
    authDomain: 'expense-tracker-70ad9.firebaseapp.com',
    storageBucket: 'expense-tracker-70ad9.firebasestorage.app',
    measurementId: 'G-DCGS0YL1SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBa-wU-TmijrrnAwdq_t1FkllV2GNqbPA',
    appId: '1:584735660993:android:040acfae039319598f2d40',
    messagingSenderId: '584735660993',
    projectId: 'expense-tracker-70ad9',
    storageBucket: 'expense-tracker-70ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsJoWL716OfS2F6D3MA7C8MDi7aN2aog',
    appId: '1:584735660993:ios:c260141c9555feb28f2d40',
    messagingSenderId: '584735660993',
    projectId: 'expense-tracker-70ad9',
    storageBucket: 'expense-tracker-70ad9.firebasestorage.app',
    iosBundleId: 'com.example.expensetarckerappv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGsJoWL716OfS2F6D3MA7C8MDi7aN2aog',
    appId: '1:584735660993:ios:c260141c9555feb28f2d40',
    messagingSenderId: '584735660993',
    projectId: 'expense-tracker-70ad9',
    storageBucket: 'expense-tracker-70ad9.firebasestorage.app',
    iosBundleId: 'com.example.expensetarckerappv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ZK1j9-lzlYvnjbXS29DxemNcPf1whWM',
    appId: '1:584735660993:web:e93369dc4b4d283d8f2d40',
    messagingSenderId: '584735660993',
    projectId: 'expense-tracker-70ad9',
    authDomain: 'expense-tracker-70ad9.firebaseapp.com',
    storageBucket: 'expense-tracker-70ad9.firebasestorage.app',
    measurementId: 'G-1RGKB9QBK1',
  );
}
